### ISSUE TITLE
Проблема. Пересылка сообщений с ссылкой на видео работает некорректно.

### ISSUE THREAD

**Issue by CLICUS** [Hlebushek2020/Volt#26]
![image](https://github.com/Hlebushek2020/Volt/assets/63193749/38df3b00-7b8c-438b-a0a0-394a95b1c45e)

> Видео было в отдельном embed, но он что то не подгрузился, и ссылка в текст перенеслась.

**Comment by Hlebushek2020** [comment]
Воспроизведение:
1) Отправить сообщение вида: https://cdn.discordapp.com/attachments/844239275478089728/1106889752239677521/render11078682.mp4
2) Переслать его через бота
