### ISSUE TITLE
Добавление реакция на пересылку сообщений по ссылке.

### ISSUE THREAD

**Issue by CLICUS** [Hlebushek2020/Volt#6]
Добавить реакцию на пересланное сообщение ссылкой, для того чтобы обычные люди могли если что убрать это сообщение, если вдруг не надо. **(Желательно сделать эту эмоцию на 1-2 минуты)** Смайл можно использовать этот "❎"

**Comment by Hlebushek2020** [comment]
Дополнительно добавил: 
- возможность админам удалять через реакцию любое сообщение бота
- возможность в личных сообщения удалять сообщения бота, так же через реакцию
